# Site settings
title: Bruno Zeraik
email: brunozrk@gmail.com
description: Remando contra a maré, desenvolvendo software sem café!
twitter_username: brunozrk
github_username:  brunozrk

url: http://brunozrk.github.io/

# Build settings
markdown: kramdown

# Google Analytics
ga_tracking_id : 'UA-59323333-3'

# Comments
disqus_shortname: brunozeraik